### ISSUE TITLE
VS 2015 intellisense breaks on C1 Datatypes

### ISSUE THREAD

**Issue by NerdBrick** [Orckestra/C1-CMS#139]
My apologies for not finding the perfect repro case just yet. Plus I understand this might be a bug in VS 2015. I'm currently using the released version of C1 5.0 and VS 2015 Ent. 

When working with C1 Data.Get() on my Datatyes in the Razor view, the intellisense (statement completion) will work for a little while, and some action (haven't figured this part out yet) will break intellisense on my Global Datatypes.  It broke once when I saved the web.config and another time when I did a refresh on the Razor folder to include newly created files. Once it did it to me when I was in the C1 Console editing content and came back to VS and it was broken again. 

Closing and reopening the solution will fix the problem. 

I will continue to look for a 100% repro case, but I thought I would put this out there to get feedback from other users. Like I said, it could just be a bug in VS. 

NOTE: I first noticed this when I trying out the demo in this video. 
https://www.youtube.com/watch?v=lwG338ecwsM

**Comment by napernik** [comment]
Hi @NerdBrick 

The likely reason why intellisense stops working is that when you restart C1, it often regenerates /Bin/Composite.Generated.dll file. Most likely explanation is that visual studio unloads the type data for the old version of Composite.Generate.dll and doesn't load a new one, or fails it to load because it is done while dll is still being copied. 

We don't see this problem often, as we use ReSharper and it seem to provide its own intellisense engine.

**Comment by NerdBrick** [comment]
I too use ReSharper, but statement completion is broken with it too. The user defined code goes red in the Razor engine.
The best fix we have at the moment is close and reopen the solution.

**Comment by napernik** [comment]
Closed as it is unlikely possible to make a fix withing C1 code to address it. It seems more of ReSharper/VisualStudio intellisense issue.
