### ISSUE TITLE
Recursion in TreeDefinitions doesn't work

### ISSUE THREAD

**Issue by aeont** [Orckestra/C1-CMS#14]
If we need build a tree where DataElements have childrens of same type (recursion) it's not possible to do, except writing own provider. It's really weird, cause MediaFolders and Pages have such support.

i.e

Category1
   Category1.2
       Product.1.2.1
       Category1.2.1
       Category1.2.2
Category2
   Product.2
   Category2.1
   Category2.2

**Comment by mawtex** [comment]
I expect you refer to the "Tree Definitions" feature - this does indeed not have support for recursive structures. You are probably able to create the effect by nesting the same element structure X levels down, always filtering on the element above, but there would be an upper limit to recursion (X).

Page and media providers are coded (not created by the xml based "Tree Definitions"), so there is no restriction on recursion there.

**Comment by burningice2866** [comment]
@aeont its actually not that scary to write your own ElementProviders as soon as you get the hang of it. I'm doing it all the time for my C1Contrib packages and even started making my own small ElementProvider-framework, so the provider itself is really simple and then i use MEF to add elements to it.

See for instance the provider for FormBuilder which is 100% pluggable in regards of adding elements and actions.

https://bitbucket.org/burningice/compositec1contrib.formbuilder/src/6b3e044d54118dc7a53680adc1dd2fd77b0e0a76/FormBuilder/C1Console/ElementProvider/FormBuilderElementProvider.cs?at=default&fileviewer=file-view-default

What you need to understand that every element has a Token, but as soon as you get that, its easy to build unlimited nested and recursive trees using this model, since for each Token you have one or more corresponding providers that provides Elements for that Token, and for each of those ElementTokens you again have providers that provide Elements and then you can go on for ever.

Ie. at the root we have a Element with the token of FormElementProviderEntityToken. Now this is the handler/provider for that token https://bitbucket.org/burningice/compositec1contrib.formbuilder/src/6b3e044d54118dc7a53680adc1dd2fd77b0e0a76/FormBuilder/C1Console/ElementProvider/FormElementProviderEntityTokenHandler.cs?at=default&fileviewer=file-view-default

The trick here is to return a Folder-element while the name of a form contains a dot ".", just like the Functions-tree does it, and here comes the recursion. As long as the handler for the FolderToken keeps returning more Folders, you can have an unlimited nested tree.

https://bitbucket.org/burningice/compositec1contrib.formbuilder/src/6b3e044d54118dc7a53680adc1dd2fd77b0e0a76/FormBuilder/C1Console/ElementProvider/NamespaceFolderEntityTokenHandler.cs?at=default&fileviewer=file-view-default

The beauty of this framework is that its dead easy for anyone at anytime to inject their own elements or actions to an existing tree, all you need to know is what EntityTokens the different elements has.
