### ISSUE TITLE
C1 console: Website root page bug

### ISSUE THREAD

**Issue by aeont** [Orckestra/C1-CMS#195]
We have 2 pages:
1) Page title: Home, Menu title: Home2
2) Page title: Test, Menu title: Test2
![image](https://cloud.githubusercontent.com/assets/11037398/16390445/b134fdf0-3c57-11e6-8737-b57fa3d3284e.png)
![image](https://cloud.githubusercontent.com/assets/11037398/16390456/b8a90310-3c57-11e6-9c11-bb94c442f3d7.png)

In admin we have:
![image](https://cloud.githubusercontent.com/assets/11037398/16390470/cbcc5faa-3c57-11e6-8e7b-2f12918f74e2.png)

Expected: Home should be Home2. I.e. act like other pages.

**Comment by wwwysocki** [comment]
This is intended. All the pages show teir menu titles in the page tree, except for the home page.

The home page normally allows an empty menu title, and under normal conditions, it comes with an empty title, allowing URLs like

http://contoso.com/Test2, rather than http://contoso.com/Home/Test2

Please see http://docs.composite.net/Configuration/UrlConfiguration/Empty-URL-Title

**Comment by mawtex** [comment]
For the history books let me add that we originally had the behavior suggested by @aeont and got negative feedback on it. When hosting multiple sub-sites that has menu titles, often they would have a generic title like "Home" making it practically impossible to distinguish them.
