### ISSUE TITLE
Page metatype display "always inherit" not working as expected. It doesn't show field values on sub-pages under "Metadata" tab.

### ISSUE THREAD

**Issue by DBailey635** [Orckestra/C1-CMS#32]
I'm not sure if this is a bug, or if I'm interpreting the documentation incorrectly.

I have created a Page Metatype with two optional fields. I have then gone into the Content perspective and right-clicked my website homepage to "Add metadata field" from the contextual menu. In the "Edit Page Metadata Field" panel, I have selected "Always inherit" in the "Inherit display" field, and "Start display from" is set to "this item". On the "Next" panel screen, I left both field values empty.

Returning to the website content tree, I then opened and edited my website homepage. Selecting the "Metadata" tab, I entered two values into the two optional fields.

Assuming "always inherit" means that the value entered in my homepage will propagate through to the sub-pages, I was surprised to see that in the sub-pages, both fields were empty.

The FAQ at:

https://docs.composite.net/Data/DataFAQ?q=How+can+I+inherit+a+meta+type+when+added+to+pages%3F

... says that "By default, “Always inherit” is selected, which means that the meta type will be inherited on sub-pages of all levels in respect to the current page."

However, the field values do not appear to propagate through to sub-pages under the "Metadata" tab.

**Comment by DBailey635** [comment]
I should note, if I don't leave both field values empty on the initial "Add metadata field" setup process, the values entered do propagate across all child pages, but subsequent changes to those fields don't propagate.

**Comment by mawtex** [comment]
This is by design - the "Always Inherit" option shown below "Metadata field group visibility, inherit display" is controlling where the field will be shown. It does not control how data inheritance.

If you apply a new field to an existing structure, you can set a default value on all affected pages, and this value is then copied to all those pages.

To get the effect of an inherited value the way to go would be to make a field optional and when querying for data, if a value is missing on the current page, crawl up the sitemap and locate the first set value.
