### ISSUE TITLE
Create room on Gitter

### ISSUE THREAD

**Issue by burningice2866** [Orckestra/C1-CMS#90]
There should be a room on https://gitter.im/Orckestra/C1-CMS to facilitate a more agile interaction towards the community

**Comment by aeont** [comment]
@burningice2866 great idea, but doubt they will invest time into it, cause even 'official' channels response time is slow or just untracked - CodePlex, Git bug reports, Stack Overflow. Great example here: http://stackoverflow.com/search?tab=newest&q=Composite%20C1

**Comment by aeont** [comment]
most of questions is simple and it's just lost PR chance to leave 'trace of C1' in this media channels.

**Comment by burningice2866** [comment]
@aeont i'm afraid you're right, but as long as i'm using C1 will i keep suggesting, contributing and believe that things can change.

**Comment by mawtex** [comment]
@aeont we might have fundamentally different views on what open source / community is - but are you not supposed to be one of the people who ensure that questions on http://stackoverflow.com/search?tab=newest&q=Composite%20C1 gets answered? But instead of doing it and animating more people to do it, you just complain that the core group does no do it? #seriouslywtf

@burningice2866 is there a good example of gitter public rooms working well, and what unadressed problems do you see it solving / what existing systems do you see we can replace with it?

**Comment by burningice2866** [comment]
@mawtex its simply a more realtime colloboration experience, not replacing any existing systems.

I've previously created and advertised a room on JabbR which did exist for a while, but there was no official advertisement of the room from Your part, which made it up-hill, to say the least. Gitter is not that different from JabbR, except for a better integration with Github, issues, code commits etc.

Rooms that i'm following:

https://gitter.im/gulpjs/gulp
https://gitter.im/twbs/bootstrap
https://gitter.im/Microsoft/TypeScript

**Comment by mawtex** [comment]
I've created the room. If it end up as a ghost town I'll close it again, so fill it with funky vibes and life!

https://gitter.im/Orckestra/C1-CMS
