### ISSUE TITLE
Console - Upper case username bug

### ISSUE THREAD

**Issue by aeont** [Orckestra/C1-CMS#91]
When you create user from console, for example Vlad, it's become 'vlad' in database. When I login via console - with 'Vlad' user seems logged in, but console not loading, cause in database key is 'Vlad'.

**Comment by InnaBoitsun** [comment]
Hi,
I re-tested and login name is not case-sensitive. When you create a user with name 'Vlad', then you can login with any 'vlad', 'VLAD' or  'Vlad' ....  and it looks like it by design. 

There is another bug. The console not loading, when a created user doesn't have any Permissions (doesn't belong to any User Group). So I will report another bug.

**Comment by aeont** [comment]
@InnaBoitsun My specific scenario - creating user via C#. C1 force username to lowercase.. and than key mismatch happens. So you HAVE TO use username lowercase.

**Comment by InnaBoitsun** [comment]
It is by design, that is database Username in lowercase.
